version: "3"
services:
  web:
    build: .
    restart: unless-stopped
    environment:
      - SECRET_KEY=example123
      - OAUTH_CLIENT_ID=mock-client-id
      - OAUTH_CLIENT_SECRET=mock-client-secret
      - OAUTH_OPENID=http://oauth.localhost:8080/issuer1/.well-known/openid-configuration
    ports:
      - "8000:8000"

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.8
    hostname: oauth.localhost
    ports:
      - "8080:8080"
    # this
    # network_mode: "host"
    volumes:
      - ./tests/resources/config.json:/app/config.json
      - ./tests/resources/login.example.html:/app/login/login.example.html
      - ./tests/resources/static/:/app/static/
    environment:
      LOG_LEVEL: "debug"
      SERVER_PORT: 8080
      # SERVER_HOSTNAME: localhost
      JSON_CONFIG_PATH: /app/config.json
