[project]
name = "beanhub"
version = ""
description = ""
authors = [
    {name = "Norbert Szulc", email = "norbert@not7cd.net"},
]
dependencies = [
    "flask>=3.0.3",
    "authlib>=1.3.1",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "none"}

